import React from "react";
import { View, Text } from "react-native";
import { cn } from "../../utils";

export interface AIPoweredSummaryCardProps {
    title?: string;
    summary: string;
    className?: string;
}

export const AIPoweredSummaryCard: React.FC<AIPoweredSummaryCardProps> = ({
    title,
    summary,
    className,
}) => {
    return (
        <View
            className={cn(
                "bg-[#1A2E3D] border border-ui-border rounded-2xl p-5",
                className
            )}
        >
            <View className="flex-row items-center mb-3">
                <Text className="text-xl mr-2">🤖</Text>
                <Text className="text-[#4A90E2] text-lg font-bold">
                    {title || "AI-Powered Summary"}
                </Text>
            </View>

            <Text className="text-[#C2C7D0] text-base leading-6 mb-4">
                {summary}
            </Text>

            <Text className="text-text-tertiary text-xs italic">
                This summary is generated by AI.
            </Text>
        </View>
    );
};
